config/routes.rb
Rails.application.routes.draw do

  resources :sessions,  only: [:new, :destroy]
  get '/auth/:provider/callback' => "sessions#handle_oauth"

  resources :intro, only: [:index]

  resources :games, only: [:index] do
    get "/play/:throw", action: :play, on: :collection
  end


  root to: 'intro#index'

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :authentication_providers
  has_many :facebook_providers, -> { facebook }, through: :authentication_providers
end

app/models/account_manager.rb
class AccountManager

  def self.find_by_omniauth_or_create!(oauth_params)
    auth = AuthenticationProvider.
      where(uid: oauth_params["uid"]).
      first_or_initialize(
        provider:   oauth_params["provider"],
        avatar_url: oauth_params.dig("info", "image")
      )


    if auth.account.blank?
      Account.create.tap do |account|
        auth.account = account
        auth.save!
      end
    else
      auth.account
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication_provider.rb
class AuthenticationProvider < ApplicationRecord

  PROVIDERS = [ FACEBOOK = :facebook ]

  belongs_to :account

  scope :facebook, -> { where(provider: FACEBOOK) }

  validates :uid, :provider, :avatar_url, presence: true
  validates :uid, uniqueness: true
end

app/models/game_play.rb
# This class knows how to plays the game.
class GamePlay

  class InvalidThrowError < StandardError; end

  DEFEAT  = {rock: :scissors, paper: :rock, scissors: :paper}
  THROWS  = DEFEAT.keys
  RESULTS = [ TIE = :tie, WON = :won, LOSE = :lose ]

  attr_reader :player_throw, :on_error

  def initialize(player_throw, &on_error)
    @player_throw = player_throw.to_sym
    @on_error     = on_error
    validate_throw
  end

  # Makes sure the user throw is valid
  def validate_throw
    return if THROWS.include?(player_throw)
    fail InvalidThrowError, "You must throw one of the following: #{THROWS}"
  end

  # finds the winner
  def play
    result, result_message =  if player_throw == computer_throw
                                [TIE, "You tied with the computer. Try again!"]
                              elsif computer_throw == DEFEAT[player_throw]
                                [WON, "Nicely done; #{player_throw} beats #{computer_throw}!"]
                              else
                                [LOSE, "Ouch; #{computer_throw} beats #{player_throw}. Better luck next time!"]
                              end

    {computer_throw: computer_throw, result: result, result_message: result_message}
  end

  # system throw
  def computer_throw
    @computer_throw ||= THROWS.sample
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_account

  def current_account
    @account ||= Account.find_by(id: session[:account_id])
  end

  def require_account
    unless current_account
      redirect_to root_path
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  rescue_from GamePlay::InvalidThrowError do
    render json: {error: 'Invalid throw error'}, status: 422
  end

  def index
  end

  def play
    result = GamePlay.new(params[:throw]).play
    render json: result
  end
end

app/controllers/intro_controller.rb
class IntroController < ActionController::Base
  layout "application"

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base

  def new
    redirect_to "/auth/facebook"
  end

  def handle_oauth
    @account = AccountManager.find_by_omniauth_or_create!(request.env['omniauth.auth'])
    session[:account_id] = @account.id

    if @account
      redirect_to games_path
    else
      redirect_to intro_path
    end
  end

  def destroy
    session[:account_id] = @account = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/games/index.html.erb
<h1>Rock, Paper or Scissors Game</h1>
<h2>Computer vs. You</h2>

<div id="left">
  <span id="player-move"> ? </span>
</div>

<div id="right">
  <span id="computer-move"> ? </span>
</div>

<div style="clear:both;"></div>

<div id="move">
  <a class="scissors" data-move="scissors">  ✄ </a>
  <a class="rock" data-move="rock">   ✺ </a>
  <a class="paper" data-move="paper">   ❏ </a>
  <p id="move-choosen"> Paper </p>
</div>

<div id="notification">
  Make a choice!
</div>

app/views/intro/index.html.erb
<%= link_to new_session_path, style: "text-decoration:none;color:#838B8B;" do %>
  <h1>Start Playing Today!</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8">
    <title>Rock, Paper or Scissors Game | @klebervirgilio</title>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application' %>
  </head>

  <body>
    <div id="wrapper">
      <%= yield %>
    </div>

    <%= javascript_include_tag :application %>
  </body>
</html>